### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by amirouche** [ecraven/r7rs-coverage#4]
I plan to re-use your work as part of scheme-live.

Do you mind adding a LICENSE file? Possibly SRFI license, see https://github.com/scheme-live/live/pull/7.

NB: You will be added to the contributors of scheme live, if so is your desire.

**Comment by amirouche** [comment]
Are those tests based on larceny tests?

**Comment by ecraven** [comment]
The actual "test" snippets are all mine, the `coverage` script is based on larceny's `bench` script.
I will add a license file, but need a few days to figure out the details.

**Comment by amirouche** [comment]
Nevermind, I will create a test suite on my own.
